In [1]:
"""
2021.10.13 18.39PM
"""

'\n2021.10.13 18.39PM\n'

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
"""
tf.where(条件语句，真返回A，假返回B)
实际上就是三目运算
"""
a = tf.constant([1,2,3,4,5])
b = tf.constant([0,1,2,8,7])
c = tf.where(tf.greater(a, b), a, b) #若a>b，返回a对应位置的元素，否则返回b对应位置的元素
c

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 8, 7])>

In [4]:
"""
np.random.RandomState.rand(维度)
用于返回{0， 1）之间的随机数
"""
rdm = np.random.RandomState(seed = 1) #seed函数使每次生成的随机数都相同，取消seed函数每次生成的随机数都会变化
d = rdm.rand() #返回一个标量
e = rdm.rand(2,3) #返回2行3列随机数矩阵
print("rdm:", rdm)
print("d:", d)
print("e:", e)

rdm: RandomState(MT19937)
d: 0.417022004702574
e: [[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]


In [5]:
"""
np.vstack(数组1, 数组2)
将两个数组按垂直方向叠加
vstack:虚拟堆栈
"""
f = np.vstack((a ,b))
f

array([[1, 2, 3, 4, 5],
       [0, 1, 2, 8, 7]])

In [42]:
"""
np.mgrid[], .ravel(), np.c_[]
np.mgrid[起始值：结束值：步长, 起始值：结束值：步长, ...]（[起始值:结束值)）:等差数组
x.ravel()：将x变为一维数组，（把‘.’前变量拉直）
np.c_[数组1， 数组2， ...]：使返回的间隔数值点配对
"""
g, h = np.mgrid[1:3:1, 2:4:0.5]
grid = np.c_[g.ravel(), h.ravel()]
print("g:", g)
print("h:", h)
grid #我自己的理解就是笛卡尔积

g: [[1. 1. 1. 1.]
 [2. 2. 2. 2.]]
h: [[2.  2.5 3.  3.5]
 [2.  2.5 3.  3.5]]


array([[1. , 2. ],
       [1. , 2.5],
       [1. , 3. ],
       [1. , 3.5],
       [2. , 2. ],
       [2. , 2.5],
       [2. , 3. ],
       [2. , 3.5]])