In [1]:
"""
2021.10.09 11:41AM
"""

'\n2021.10.09 11:41AM\n'

In [6]:
import tensorflow as tf
import numpy as np

In [2]:
"""
张量：多维数组（列表）  阶：张量的维度
维数     阶    名字
0-D      0     标量
1-D      1     向量
2-D      2     矩阵
n-D      n     张量     判断张量是几阶，就看张量的方括号有几个
张量可以表示0-n阶的数组
"""

'\n张量：多维数组（列表）  阶：张量的维度\n维数     阶    名字\n0-D      0     标量\n1-D      1     向量\n2-D      2     矩阵\nn-D      n     张量     判断张量是几阶，就看张量的方括号有几个\n张量可以表示0-n阶的数组\n'

In [4]:
"""
创建tensorflow
constant 第一个参数指定张量内容，第二个参数指定数据类型
张量的形状，看shape的逗号隔开了几个数字，逗号隔开了几个数字，张量就是几维的
下面例子中，逗号隔开了一个数字，表示张量是一维的，数字为2，表明张量里有两个元素
"""
a = tf.constant([1,5], dtype=tf.int64)
print(a)
print(a.dtype)
print(a.shape)

tf.Tensor([1 5], shape=(2,), dtype=int64)
<dtype: 'int64'>
(2,)


In [8]:
"""
将numpy的数据类型转换为Tensor数据类型
"""
b = np.arange(0,5)
c = tf.convert_to_tensor(b, dtype=tf.int64)
print(b)
print(c)

[0 1 2 3 4]
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)


In [13]:
"""
创建全为0的张量：zeros
创建全为1的张量：ones
创建全为指定值的张量：fill
"""
d = tf.zeros([2,3])
e = tf.ones(4)
f = tf.fill([2,2], 9)
print(d)
print(e)
print(f)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)
tf.Tensor(
[[9 9]
 [9 9]], shape=(2, 2), dtype=int32)


In [17]:
"""
随机数
第一个参数是维度，第二个参数mean是均值，第三个参数stddev是标准差
"""
#生成正态分布的随机数，默认均值是0，标准差是1
g = tf.random.normal([2,3], mean=0.5, stddev=1)
print(g)
#生成截断式正态分布的随机数（生成的随机数更集中）
#下面例子生元素符合以0.5为均值，1为标准差的随机数，且这些元素都在两倍标准差之内，数据向0.5集中
h = tf.random.truncated_normal([2,2], mean=0.5, stddev=1)
print(h)
"""
生成指定维度的均匀分布随机数
第一个参数是维度，第二个参数是最小值哦，第三个参数是最大值
"""
i = tf.random.uniform([2,2], minval=0, maxval=1)
print(i)

tf.Tensor(
[[0.59092563 0.92152536 0.8283225 ]
 [1.217311   0.4838808  0.37289768]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-1.0572299  -0.10932344]
 [ 0.6972113   0.3234763 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.73625386 0.8662269 ]
 [0.8192158  0.74346757]], shape=(2, 2), dtype=float32)


In [18]:
"""
强制tensor转换为该数据类型
tf.cast(张量名， 数据类型)
计算张量维度最小值
tf.reduce_min(张量名)
计算张量维度上元素最大值
tf.reduce_max(张量名)
"""
x1 = tf.constant([1,2,3], dtype=tf.float32)
print(x1)
x2 = tf.cast(x1, tf.int32)
print(x2)
print(tf.reduce_min(x2), tf.reduce_max(x2))

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32) tf.Tensor(3, shape=(), dtype=int32)


In [21]:
"""
axis等于0、1控制执行维度
axis=0 代表跨行（经度） sxis=1 代表跨列（纬度）
不指定axis，则所有元素参与计算
"""
x3 = tf.constant([[1,2,3,],
                  [2,2,3]])
print(x3)
print(tf.reduce_mean(x3))
print(tf.reduce_sum(x3, axis=1))
print(tf.reduce_sum(x3, axis=0))

tf.Tensor(
[[1 2 3]
 [2 2 3]], shape=(2, 3), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)
tf.Tensor([3 4 6], shape=(3,), dtype=int32)


In [25]:
"""
tf.Variable 将变量标记为“可训练”被标记变量会在反向传播中记录梯度信息
在神经网络中，常用该函数标记带训练参数
"""
w = tf.Variable(tf.random.normal([2,2], mean=0, stddev=1))
print(w)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.5192878,  0.5431787],
       [-1.6416678,  2.5416644]], dtype=float32)>


In [26]:
"""
  加         减            乘            除
tf.add   tf.subtract   tf.multiply   tf.divide
只有维度相同的张量才可以做四则运算
   平方       次方     开方
tf.square   tf.pow   tf.sqrt
 矩阵乘
tf.matmul
"""

'\n  加         减            乘            除\ntf.add   tf.subtract   tf.multiply   tf.divide\n只有维度相同的张量才可以做四则运算\n   平方       次方     开方\ntf.square   tf.pow   tf.sqrt\n 矩阵乘\ntf.matmul\n'

In [27]:
"""
tf.data.Dataset.from_tensor_silces((输入特征,标签))
切分传入张量的第一维度，生成输入特征/标签对，构建数据集
（Numpy和Tensor格式都可以用该语句读入数据）
"""
feature = tf.constant([12,33,10,17])
labels = tf.constant([0,1,1,0])
dataset = tf.data.Dataset.from_tensor_slices((feature, labels))
print(dataset)
for element in dataset:
    print(element)

<TensorSliceDataset shapes: ((), ()), types: (tf.int32, tf.int32)>
(<tf.Tensor: shape=(), dtype=int32, numpy=12>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=33>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=17>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


In [28]:
"""
tf.GradientTape
实现某个函数对指定参数进行求导运算
with tf.GradientTape() as tape:
    若干个计算过程
grad = tape.gradient(函数，对谁求导)
"""
with tf.GradientTape() as tape:
    w1 = tf.Variable(tf.constant(3.0))
    loss = tf.pow(w1,2)
grad = tape.gradient(loss, w1)
print(grad)

tf.Tensor(6.0, shape=(), dtype=float32)


In [30]:
"""
enumerate(列表名)
遍历每个元素（如列表、元组、字符串）
组合为：索引  元素
常在for循环中使用
"""
seq = ['one', 'two', 'three']
for i,element in enumerate(seq):
    print(i,element)

0 one
1 two
2 three


In [34]:
"""
tf.one_hot
独热编码：在分类问题中，常用独热编码做标签，标记类型：1表示是，0表示非
（0表示狗尾草鸢尾，1杂色鸢尾，2弗吉尼亚鸢尾）
标  签： 1
独热码： 0          1           0
"""
classes = 3
lbs = tf.constant([1,1,0])
output =  tf.one_hot(lbs,depth=classes)
print(output)

tf.Tensor(
[[0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]], shape=(3, 3), dtype=float32)


In [35]:
"""
tf.nn.softmax
使输出符合概率分布
"""
y = tf.constant([1.01,2.01,-0.66])
y_pro = tf.nn.softmax(y)
print("After softmax,y_pro is", y_pro)

After softmax,y_pro is tf.Tensor([0.25598174 0.6958304  0.0481878 ], shape=(3,), dtype=float32)


In [37]:
"""
assign_sub
赋值操作，更新参数值并返回
调用assign_sub前，先用Variable定义变量w为可训练（可自更新）
w.assign_sub(w要自减的内容)
"""
w3 = tf.Variable(4)
w3.assign_sub(1)     #w- = 1 即 w = w-1 
print(w3)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>


In [39]:
"""
tf.argmax(张量，axis=操作抽)
返回张量延指定维度最大的索引
"""
test = np.array([[1,2,3], [2,3,4], [5,4,3], [8,7,2]])
print(test)
print(tf.argmax(test, axis = 0))
print(tf.argmin(test ,axis = 1))

[[1 2 3]
 [2 3 4]
 [5 4 3]
 [8 7 2]]
tf.Tensor([3 3 1], shape=(3,), dtype=int64)
tf.Tensor([0 0 2 2], shape=(4,), dtype=int64)
